set_schedule:
  name: Set weekly schedule
  description: >-
    Set the 7×24 weekly program for a TermoWeb heater. The program is a list of
    168 integers, where each value corresponds to one hour of the week starting
    Monday 00:00. Use 0 for the cold preset, 1 for the night preset and 2 for
    the day preset.
  target:
    entity:
      domain: climate
      integration: termoweb
  fields:
    prog:
      name: Program
      description: >-
        A list of 168 integers (0, 1 or 2) representing the heater’s weekly
        schedule. Index 0 is Monday 00:00, index 1 is Monday 01:00, and so on.
      example: '[0,0,0,1,1,2,2,0,1,2,0,...]'
      required: true

set_preset_temperatures:
  name: Set preset temperatures
  description: >-
    Set the cold, night and day preset temperatures for a TermoWeb heater. You
    can either provide all three temperatures as a single list (``ptemp``) or
    specify each one separately (``cold``, ``night`` and ``day``).
  target:
    entity:
      domain: climate
      integration: termoweb
  fields:
    ptemp:
      name: Preset temperatures
      description: >-
        A list of three temperatures [cold, night, day] in the same units as
        the heater (°C or °F). If provided, this will override individual cold,
        night and day values.
      example: '[10.0, 16.0, 20.0]'
    cold:
      name: Cold preset
      description: Temperature for the cold preset (°C or °F).
      example: 10.0
    night:
      name: Night preset
      description: Temperature for the night preset (°C or °F).
      example: 16.0
    day:
      name: Day preset
      description: Temperature for the day preset (°C or °F).
      example: 20.0